set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

run '~/.tmux/plugins/tpm/tpm'

#set the prefix to Ctrl+ea
set -g prefix C-a

unbind C-b

bind C-a send-prefix

#split panes using | and -

bind | split-window -h
bind - split-window -v
unbind "'"
unbind %

#reload config file
bind r source-file ~/.config/tmux/tmux.conf

#switch panes 
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

#design tweaks

#ignore bell
set -g visual-activity off
set -g visual-bell off
set -g visual-silence off
set -g monitor-activity off
set -g bell-action none

#clock mode
setw -g mode-style 'fg=black bg=yellow bold'

#statusbar
set -g status-position bottom
set -g status-justify left
set -g status-style 'fg=yellow'

set -g status-left ''
set -g status-left-length 10

set -g status-right-style 'fg=yellow'
set -g status-right '%Y-%m-%d'
set -g status-right-length 10

set -g window-status-current-style 'fg=yellow bold'
set -g window-status-format ' #I #[fg=white]#W #[fg=yellow]#F'
set -g window-status-bell-style 'fg=yellow bg=red bold'

#messages
set -g message-style 'fg=yellow bg=red bold'
